import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    "index",
    {
      type: "doc",
      id: "overview/getting-started",
      label: "Getting Started",
    },
    {
      type: "category",
      label: "Concepts",
      collapsed: false,
      link: { type: "doc", id: "overview/index" },
      items: [
        "overview/architecture",
        "overview/authentication",
        "overview/sso",
        "overview/workplace-fqdn",
        "overview/ldap-structure",
        "overview/ldap-password-policy",
        "overview/rabbitmq",
        "overview/security",
        "overview/environments",
        "overview/npm-packages",
        "overview/glossary",
      ],
    },
    {
      type: "category",
      label: "B2C",
      collapsed: false,
      link: { type: "doc", id: "b2c/index" },
      items: [
        "b2c/account-recovery",
        "b2c/two-factor-auth",
        "b2c/account-deletion",
      ],
    },
    {
      type: "category",
      label: "B2B",
      collapsed: false,
      link: { type: "doc", id: "b2b/index" },
      items: [
        "b2b/services",
        "b2b/org-creation",
        "b2b/invitations",
        "b2b/domain-validation",
        "b2b/user-lifecycle",
        "b2b/auth",
        "b2b/app-provisioning",
        "b2b/company-shared-drive",
        "b2b/settings",
      ],
    },
    {
      type: "category",
      label: "Developer Guide",
      collapsed: true,
      link: {
        type: "generated-index",
        slug: "/developer-guide",
        description:
          "How to work inside the Twake Workplace monorepo: local development, conventions, and day-to-day workflows.",
      },
      items: [
        "overview/monorepo-guide",
        "overview/best-practices",
        "overview/ai-workflows",
        "overview/docker-compose",
      ],
    },
    {
      type: "category",
      label: "Services",
      collapsed: true,
      link: {
        type: "generated-index",
        slug: "/services",
        description:
          "Twake Workplace services split by audience: user-facing apps and the internal platform services that power them.",
      },
      items: [
        {
          type: "category",
          label: "Apps",
          collapsed: true,
          link: {
            type: "generated-index",
            slug: "/apps",
            description:
              "User-facing Twake Workplace applications: mail, chat, calendar, and Cozy.",
          },
          items: [
            {
              type: "category",
              label: "Twake Mail",
              collapsed: true,
              link: { type: "doc", id: "tmail/index" },
              items: [{ type: "autogenerated", dirName: "tmail" }],
            },
            {
              type: "category",
              label: "Twake Chat",
              collapsed: true,
              link: { type: "doc", id: "twake-chat/index" },
              items: [{ type: "autogenerated", dirName: "twake-chat" }],
            },
            {
              type: "category",
              label: "Twake Calendar",
              collapsed: true,
              link: { type: "doc", id: "tcalendar/index" },
              items: [{ type: "autogenerated", dirName: "tcalendar" }],
            },
            {
              type: "category",
              label: "Twake Drive",
              collapsed: true,
              link: { type: "doc", id: "twake-drive/index" },
              items: [{ type: "autogenerated", dirName: "twake-drive" }],
            },
            {
              type: "category",
              label: "Cozy Stack",
              collapsed: true,
              link: { type: "doc", id: "cozy-stack/index" },
              items: [{ type: "autogenerated", dirName: "cozy-stack" }],
            },
            {
              type: "category",
              label: "Cozy Admin",
              collapsed: true,
              link: { type: "doc", id: "cozy-admin/index" },
              items: [{ type: "autogenerated", dirName: "cozy-admin" }],
            },
            {
              type: "category",
              label: "Cozy Apps",
              collapsed: true,
              link: { type: "doc", id: "cozy-apps/index" },
              items: [{ type: "autogenerated", dirName: "cozy-apps" }],
            },
          ],
        },
        {
          type: "category",
          label: "Platform Services",
          collapsed: true,
          link: {
            type: "generated-index",
            slug: "/platform-services",
            description:
              "Internal platform services. Each entry below is a one-page summary that links to the full reference docs in the service's repo on GitHub.",
          },
          items: [
            {
              type: "category",
              label: "Registration",
              collapsed: true,
              link: { type: "doc", id: "registration/index" },
              items: ["registration/email-otp"],
            },
            {
              type: "category",
              label: "Cloudery",
              collapsed: true,
              link: { type: "doc", id: "cloudery/index" },
              items: [
                "cloudery/architecture",
                "cloudery/data-model",
                "cloudery/partners-offers-plans",
                "cloudery/onboarding",
                "cloudery/billing",
                "cloudery/api",
                "cloudery/local-development",
              ],
            },
            {
              type: "doc",
              id: "admin-panel-backend/index",
              label: "Admin Panel Backend",
            },
            { type: "doc", id: "ldap-rest/index", label: "LDAP REST" },
            { type: "doc", id: "dashboard/index", label: "Dashboard" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Deployment",
      collapsed: true,
      link: {
        type: "generated-index",
        slug: "/deployment",
        description:
          "Ways to deploy Twake Workplace: Docker Compose release image, B2B multi-tenant, CI/CD pipelines.",
      },
      items: [
        {
          type: "category",
          label: "Twake Workplace Docker",
          collapsed: true,
          link: { type: "doc", id: "twake-workplace-docker/index" },
          items: [{ type: "autogenerated", dirName: "twake-workplace-docker" }],
        },
        {
          type: "category",
          label: "B2B Deployment",
          collapsed: true,
          link: { type: "doc", id: "b2b-deployment/index" },
          items: [{ type: "autogenerated", dirName: "b2b-deployment" }],
        },
        {
          type: "category",
          label: "CI/CD",
          collapsed: true,
          link: { type: "doc", id: "ci-cd/index" },
          items: [{ type: "autogenerated", dirName: "ci-cd" }],
        },
      ],
    },
    {
      type: "category",
      label: "Reference",
      collapsed: true,
      link: {
        type: "generated-index",
        slug: "/reference",
        description: "Architecture decision records and operational scripts.",
      },
      items: [
        {
          type: "category",
          label: "ADRs",
          collapsed: true,
          link: { type: "doc", id: "adrs/index" },
          items: [{ type: "autogenerated", dirName: "adrs" }],
        },
        {
          type: "category",
          label: "Scripts",
          collapsed: true,
          link: { type: "doc", id: "scripts/index" },
          items: [{ type: "autogenerated", dirName: "scripts" }],
        },
      ],
    },
  ],
};

export default sidebars;
